import pytest
import time
from faker import Faker
from selenium import webdriver
from selenium.webdriver.common.by import By
import pandas as pd
import os
from datetime import datetime

@pytest.fixture(scope="module")
def org_login():
    driver = webdriver.Chrome()
    driver.maximize_window()
    file_path = r"D:\HPB_Testcase\logindetails\login info.xlsx"
    df = pd.read_excel(file_path)
    url = df.iloc[0, 1]
    org_userid = df.iloc[1, 1]
    org_pass = df.iloc[1, 2]
    otp = df.iloc[1, 3]
    driver.get(url)
    driver.implicitly_wait(100)
    driver.find_element(By.XPATH, "//div[@class='login-form']//div[1]//label[1]").send_keys(org_userid)
    driver.find_element(By.XPATH, "//div[@class='divisions']//div[2]//label[1]//input[1]").send_keys(org_pass)
    driver.find_element(By.XPATH, "//input[@value='Sign In']").click()
    time.sleep(5)
    driver.find_element(By.XPATH, "//input[@id='inp']").send_keys(otp)
    driver.find_element(By.XPATH, "//input[@value='Submit']").click()
    time.sleep(5)
    yield driver  # Yielding the driver instance
    time.sleep(5)
    driver.quit()

@pytest.fixture
def take_screenshot(org_login, request):
    """Fixture to capture a screenshot at specific points in the test."""
    driver = org_login
    test_name = request.node.name
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    screenshots_dir = r"D:\HPB_Testcase\screenshots/alerts_Nudges"

    os.makedirs(screenshots_dir, exist_ok=True)

    def _screenshot():
        file_name = f"{test_name}_{timestamp}.png"
        file_path = os.path.join(screenshots_dir, file_name)
        driver.save_screenshot(file_path)
        print(f"Screenshot saved at {file_path}")

    return _screenshot


@pytest.hookimpl(tryfirst=True, hookwrapper=True)
def pytest_runtest_makereport(item, call):
    """Capture a screenshot if a test fails."""
    outcome = yield
    report = outcome.get_result()

    if report.when == "call" and report.failed:
        driver = item.funcargs.get('org_login')
        if driver:
            test_name = item.name
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            screenshots_dir = r"D:\HPB_Testcase\screenshots/alerts_Nudges"
            os.makedirs(screenshots_dir, exist_ok=True)
            file_name = f"{test_name}_failed_{timestamp}.png"
            file_path = os.path.join(screenshots_dir, file_name)
            driver.save_screenshot(file_path)
            print(f"Screenshot for failed test saved at {file_path}")

def test_Nudge_and_Alert_page(org_login, take_screenshot):
    driver = org_login
    driver.find_element(By.XPATH, "//span[normalize-space()='Programme Management']").click()
    driver.find_element(By.XPATH, "//a[normalize-space()='Alerts/Nudges Template']").click()
    time.sleep(2)
    take_screenshot()

def test_Create_Nudge(org_login, take_screenshot):
    driver = org_login
    fake = Faker()  # Specify 'en_GB' for UK locale
    global template_name
    template_name = fake.name()
    description = fake.paragraph()
    title = fake.name()
    message = fake.sentence()
    step_data = int(fake.random_number(4))
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class='add-patient-btn']").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-add-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[1]/label/input").send_keys(template_name)
    driver.find_element(By.XPATH, "//*[@id='add-alert-template']/div/div/div/div/app-add-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[2]/div[2]/label[2]/span").click()
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-add-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[4]/label/textarea").send_keys(description)
    time.sleep(2)
    driver.find_element(By.XPATH, "//img[@src='./assets/images/downarrow.png']").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "//*[@id='add-alert-template']/div/div/div/div/app-add-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[5]/app-dropdown/div/div/ul/li[1]/span").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//body[1]/app-root[1]/div[3]/app-view-alert-templates[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/app-add-alert-template[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/app-alert-rules[1]/form[1]/div[6]/app-jdm-editor[1]/div[1]/decision-table[1]/div[1]/div[2]/table[2]/thead[1]/tr[1]/th[2]/div[1]/div[2]/button[1]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//span[normalize-space()='Edit column']").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//*[@id='field-update-dialog']/div[1]/div/div[2]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "/html/body/div[9]/div/div/div/ul/li[2]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "/html/body/div[9]/div/div/div/ul[2]/li[1]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "/html/body/div[9]/div/div/div/ul[3]/li[1]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-add-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[6]/app-jdm-editor/div/decision-table/div/div[3]/div[2]/div/div[2]/div[3]/button[2]/span").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//body[1]/app-root[1]/div[3]/app-view-alert-templates[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/app-add-alert-template[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/app-alert-rules[1]/form[1]/div[6]/app-jdm-editor[1]/div[1]/decision-table[1]/div[1]/div[2]/table[2]/tbody[1]/tr[1]/td[2]/div[1]/input[1]").send_keys(step_data)
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class='next-btn']").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//img[@src='./assets/images/Plus Btn.png']").click()
    driver.find_element(By.XPATH, "//img[@src='./assets/images/downarrow.png']").click()
    driver.find_element(By.XPATH, "//*[@id='add-alert-template']/div/div/div/div/app-add-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-messages/div[2]/app-alert-message/div/form/div[1]/div/div[1]/ul/li[1]/label/span").click()
    driver.find_element(By.XPATH, "//*[@id='add-alert-template']/div/div/div/div/app-add-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-messages/div[2]/app-alert-message/div/form/div[1]/div/div[1]/ul/li[2]/label/span").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-add-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-messages/div[2]/app-alert-message/div/form/div[2]/label/input").send_keys(title)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-add-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-messages/div[2]/app-alert-message/div/form/div[3]/label/textarea").send_keys(message)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-add-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-messages/div[2]/app-alert-message/div/form/div[4]/div/button[2]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-add-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-messages/div[3]/div[2]").click()
    time.sleep(3)
    take_screenshot()
    time.sleep(4)
    driver.find_element(By.XPATH, "//img[@title='Refresh']").click()
    time.sleep(2)

def test_Edit_Nudge(org_login, take_screenshot):
    driver = org_login
    driver.find_element(By.XPATH,"//input[@placeholder='Search']").send_keys(template_name)
    driver.find_element(By.XPATH, "//tbody//tr//img[1]").click()
    time.sleep(2)
    fake = Faker()  # Specify 'en_GB' for UK locale
    global new_template_name
    new_template_name = fake.name()
    description = fake.paragraph()
    title = fake.name()
    message = fake.sentence()
    data = fake.random_number(2)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[1]/label/input").clear()
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[1]/label/input").send_keys(new_template_name)
    time.sleep(2)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[2]/label/textarea").clear()
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[2]/label/textarea").send_keys(description)
    time.sleep(2)
    driver.find_element(By.XPATH, "//img[@src='./assets/images/downarrow.png']").click()
    driver.find_element(By.XPATH, "//*[@id='add-alert-template']/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[3]/app-dropdown/div/div/ul/li[2]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "//div[normalize-space()='Daily']//img").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//*[@id='add-alert-template']/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[4]/div[1]/app-dropdown/div/div/ul/li[2]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "//app-dropdown[@multiple='true']//img").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "//*[@id='add-alert-template']/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[4]/div[2]/div[1]/app-dropdown/div/div/ul/li[1]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "//*[@id='add-alert-template']/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[4]/div[2]/div[2]/app-dropdown/div/div/div").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "//*[@id='add-alert-template']/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[4]/div[2]/div[2]/app-dropdown/div/div/ul/li[15]").click()
    driver.find_element(By.XPATH, "//*[@id='add-alert-template']/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[5]/app-jdm-editor/div/decision-table/div/div[2]/table[2]/thead/tr/th[2]/div[1]/div[2]/button").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "/html/body/div[8]/div/ul/li[1]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "//*[@id='field-update-dialog']/div[1]/div/div[2]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "/html/body/div[9]/div/div/div/ul/li[2]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "/html/body/div[9]/div/div/div/ul[2]/li[2]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "/html/body/div[9]/div/div/div/ul[3]/li[1]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[5]/app-jdm-editor/div/decision-table/div/div[3]/div[2]/div/div[2]/div[3]/button[2]/span").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "//*[@id='add-alert-template']/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[5]/app-jdm-editor/div/decision-table/div/div[2]/table[2]/tbody/tr/td[2]/div/input").clear()
    time.sleep(2)
    driver.find_element(By.XPATH, "//*[@id='add-alert-template']/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[5]/app-jdm-editor/div/decision-table/div/div[2]/table[2]/tbody/tr/td[2]/div/input").clear()
    time.sleep(1)
    driver.find_element(By.XPATH, "//*[@id='add-alert-template']/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[5]/app-jdm-editor/div/decision-table/div/div[2]/table[2]/tbody/tr/td[2]/div/input").send_keys(data)
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class='next-btn']").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class='alert-message-wrapper']//img[1]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "//img[@src='./assets/images/downarrow.png']").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "//*[@id='add-alert-template']/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-messages/div[1]/div/div[2]/app-alert-message/div/form/div[1]/div/div/ul/li[2]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-messages/div[1]/div/div[2]/app-alert-message/div/form/div[2]/label/input").clear()
    time.sleep(1)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-messages/div[1]/div/div[2]/app-alert-message/div/form/div[2]/label/input").send_keys(title)
    time.sleep(1)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-messages/div[1]/div/div[2]/app-alert-message/div/form/div[3]/label/textarea").clear()
    time.sleep(1)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-messages/div[1]/div/div[2]/app-alert-message/div/form/div[3]/label/textarea").send_keys(message)
    time.sleep(2)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-messages/div[1]/div/div[2]/app-alert-message/div/form/div[4]/div/button[2]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-messages/div[3]/div[2]").click()
    time.sleep(3)
    take_screenshot()
    time.sleep(4)
    driver.find_element(By.XPATH, "//img[@title='Refresh']").click()
    time.sleep(2)

def test_delete_Nudge(org_login, take_screenshot):
    driver = org_login
    driver.find_element(By.XPATH,"//input[@placeholder='Search']").send_keys(new_template_name)
    time.sleep(2)
    driver.find_element(By.XPATH, "//img[@src='./assets/images/delete.png']").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-delete-alert-templates/div/div[3]/button[2]").click()
    time.sleep(3)
    take_screenshot()
    time.sleep(4)
    driver.find_element(By.XPATH, "//img[@title='Refresh']").click()
    time.sleep(2)


def test_Create_Alerts(org_login, take_screenshot):
    driver = org_login
    fake = Faker()  # Specify 'en_GB' for UK locale
    global template_name
    template_name = fake.name()
    description = fake.paragraph()
    title = fake.name()
    message = fake.sentence()
    step_data = int(fake.random_number(4))
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class='add-patient-btn']").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-add-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[1]/label/input").send_keys(template_name)
    driver.find_element(By.XPATH, "//label[@class='custom-radio-btn']//span[@class='checkmark']").click()
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-add-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[4]/label/textarea").send_keys(description)
    time.sleep(2)
    driver.find_element(By.XPATH, "//img[@src='./assets/images/downarrow.png']").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "//*[@id='add-alert-template']/div/div/div/div/app-add-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[5]/app-dropdown/div/div/ul/li[1]/span").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//body[1]/app-root[1]/div[3]/app-view-alert-templates[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/app-add-alert-template[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/app-alert-rules[1]/form[1]/div[6]/app-jdm-editor[1]/div[1]/decision-table[1]/div[1]/div[2]/table[2]/thead[1]/tr[1]/th[2]/div[1]/div[2]/button[1]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//span[normalize-space()='Edit column']").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//*[@id='field-update-dialog']/div[1]/div/div[2]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "/html/body/div[9]/div/div/div/ul/li[2]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "/html/body/div[9]/div/div/div/ul[2]/li[1]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "/html/body/div[9]/div/div/div/ul[3]/li[1]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-add-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[6]/app-jdm-editor/div/decision-table/div/div[3]/div[2]/div/div[2]/div[3]/button[2]/span").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//body[1]/app-root[1]/div[3]/app-view-alert-templates[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/app-add-alert-template[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/app-alert-rules[1]/form[1]/div[6]/app-jdm-editor[1]/div[1]/decision-table[1]/div[1]/div[2]/table[2]/tbody[1]/tr[1]/td[2]/div[1]/input[1]").send_keys(step_data)
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class='next-btn']").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//img[@src='./assets/images/Plus Btn.png']").click()
    driver.find_element(By.XPATH, "//img[@src='./assets/images/downarrow.png']").click()
    driver.find_element(By.XPATH, "//*[@id='add-alert-template']/div/div/div/div/app-add-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-messages/div[2]/app-alert-message/div/form/div[1]/div/div[1]/ul/li[1]/label/span").click()
    driver.find_element(By.XPATH, "//*[@id='add-alert-template']/div/div/div/div/app-add-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-messages/div[2]/app-alert-message/div/form/div[1]/div/div[1]/ul/li[2]/label/span").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-add-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-messages/div[2]/app-alert-message/div/form/div[2]/label/input").send_keys(title)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-add-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-messages/div[2]/app-alert-message/div/form/div[3]/label/textarea").send_keys(message)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-add-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-messages/div[2]/app-alert-message/div/form/div[4]/div/button[2]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-add-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-messages/div[3]/div[2]").click()
    time.sleep(3)
    take_screenshot()
    time.sleep(4)
    driver.find_element(By.XPATH, "//img[@title='Refresh']").click()
    time.sleep(2)

def test_Edit_Alerts(org_login, take_screenshot):
    driver = org_login
    driver.find_element(By.XPATH,"//input[@placeholder='Search']").send_keys(template_name)
    driver.find_element(By.XPATH, "//tbody//tr//img[1]").click()
    time.sleep(2)
    fake = Faker()  # Specify 'en_GB' for UK locale
    global new_template_name
    new_template_name = fake.name()
    description = fake.paragraph()
    title = fake.name()
    message = fake.sentence()
    data = fake.random_number(2)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[1]/label/input").clear()
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[1]/label/input").send_keys(new_template_name)
    time.sleep(2)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[2]/label/textarea").clear()
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[2]/label/textarea").send_keys(description)
    time.sleep(2)
    driver.find_element(By.XPATH, "//img[@src='./assets/images/downarrow.png']").click()
    driver.find_element(By.XPATH, "//*[@id='add-alert-template']/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[3]/app-dropdown/div/div/ul/li[2]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "//div[normalize-space()='Daily']//img").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//*[@id='add-alert-template']/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[4]/div[1]/app-dropdown/div/div/ul/li[2]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "//app-dropdown[@multiple='true']//img").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "//*[@id='add-alert-template']/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[4]/div[2]/div[1]/app-dropdown/div/div/ul/li[1]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "//*[@id='add-alert-template']/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[4]/div[2]/div[2]/app-dropdown/div/div/div").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "//*[@id='add-alert-template']/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[4]/div[2]/div[2]/app-dropdown/div/div/ul/li[15]").click()
    driver.find_element(By.XPATH, "//*[@id='add-alert-template']/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[5]/app-jdm-editor/div/decision-table/div/div[2]/table[2]/thead/tr/th[2]/div[1]/div[2]/button").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "/html/body/div[8]/div/ul/li[1]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "//*[@id='field-update-dialog']/div[1]/div/div[2]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "/html/body/div[9]/div/div/div/ul/li[2]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "/html/body/div[9]/div/div/div/ul[2]/li[2]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "/html/body/div[9]/div/div/div/ul[3]/li[1]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[5]/app-jdm-editor/div/decision-table/div/div[3]/div[2]/div/div[2]/div[3]/button[2]/span").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "//*[@id='add-alert-template']/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[5]/app-jdm-editor/div/decision-table/div/div[2]/table[2]/tbody/tr/td[2]/div/input").clear()
    time.sleep(2)
    driver.find_element(By.XPATH, "//*[@id='add-alert-template']/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[5]/app-jdm-editor/div/decision-table/div/div[2]/table[2]/tbody/tr/td[2]/div/input").clear()
    time.sleep(1)
    driver.find_element(By.XPATH, "//*[@id='add-alert-template']/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-rules/form/div[5]/app-jdm-editor/div/decision-table/div/div[2]/table[2]/tbody/tr/td[2]/div/input").send_keys(data)
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class='next-btn']").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class='alert-message-wrapper']//img[1]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "//img[@src='./assets/images/downarrow.png']").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "//*[@id='add-alert-template']/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-messages/div[1]/div/div[2]/app-alert-message/div/form/div[1]/div/div/ul/li[2]").click()
    time.sleep(1)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-messages/div[1]/div/div[2]/app-alert-message/div/form/div[2]/label/input").clear()
    time.sleep(1)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-messages/div[1]/div/div[2]/app-alert-message/div/form/div[2]/label/input").send_keys(title)
    time.sleep(1)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-messages/div[1]/div/div[2]/app-alert-message/div/form/div[3]/label/textarea").clear()
    time.sleep(1)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-messages/div[1]/div/div[2]/app-alert-message/div/form/div[3]/label/textarea").send_keys(message)
    time.sleep(2)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-messages/div[1]/div/div[2]/app-alert-message/div/form/div[4]/div/button[2]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-edit-alert-template/div/div/div[2]/div[2]/div/div[2]/app-alert-messages/div[3]/div[2]").click()
    time.sleep(3)
    take_screenshot()
    time.sleep(4)
    driver.find_element(By.XPATH, "//img[@title='Refresh']").click()
    time.sleep(2)

def test_delete_Alerts(org_login, take_screenshot):
    driver = org_login
    driver.find_element(By.XPATH,"//input[@placeholder='Search']").send_keys(new_template_name)
    time.sleep(2)
    driver.find_element(By.XPATH, "//img[@src='./assets/images/delete.png']").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "/html/body/app-root/div[3]/app-view-alert-templates/div[2]/div/div/div/div/div/app-delete-alert-templates/div/div[3]/button[2]").click()
    time.sleep(3)
    take_screenshot()
    time.sleep(4)
    driver.find_element(By.XPATH, "//img[@title='Refresh']").click()
    time.sleep(2)